[helpers]

[default]
depends = []


[default.files]
"dotfiles/gitconfig" = "~/.gitconfig"
"dotfiles/.vimrc" = { target = "~/.vimrc", type = "symbolic" }
"dotfiles/cowsay" = "~/.config/cowsay"
"dotfiles/fortunes.txt" = "~/.config/fortunes.txt"
"dotfiles/omp-theme.json" = { target = "~/.config/theme.omp.json", type = "symbolic" }
"dotfiles/fastfetch.jsonc" = {target = "~/.config/fastfetch/config.jsonc", type="symbolic"}


[default.variables]
arch = "x86_64"
install_pkgs = "false"
signingkey = ""        # Only populated in local.toml

## Var values For local.toml reference
## arch="x86_64"
## arch="arm64"

[win64]
depends = []

[win64.files]
"bin/executable_sh-toy.exe" = { target = "~/.local/bin/sh-toy.exe", type = "symbolic" }
"dotfiles/profile.ps1" = "~/Onedrive/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
"dotfiles/filepilot.json" = { target ="~/AppData/Roaming/Voidstar/FilePilot/FPilot-Config.json", type = "symbolic" }

[cs2]
depends = []

[cs2.files]
# Seems like CS2 doesn't follow symlinks :(
"dotfiles/cs2_autoexec.cfg" = { target = "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Counter-Strike Global Offensive\\game\\csgo\\cfg\\autoexec.cfg", type = "template" }

[linux]
depends = []

[linux.files]
"dotfiles/.bashrc" = "~/.bashrc"
"dotfiles/.zshrc" = "~/.zshrc"
"dotfiles/profile" = "~/.profile"
"bin/executable_sh-toy" = { target = "~/.local/bin/sh-toy", type = "symbolic" }


[settings]
default_target_type = "automatic"
