name: Codeberg Mirroring
on:
  - push
  - workflow_dispatch
jobs:
  mirror-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@v0.7.0
        with:
            REMOTE: 'ssh://git@codeberg.org/FaceFTW/dotfiles.git'
            GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
            GIT_SSH_KNOWN_HOSTS: ${{ secrets.GIT_SSH_KNOWN_HOSTS }}